#!/bin/zsh
#
# name:          init-fortran-project.zsh
# version:       see VERSION.md
# synopsis:      initializes a `fortran 90` project.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2019 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-fortran-project PROJECT_NAME"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=$1

mkdir $PROJECT_NAME
cd $PROJECT_NAME
#
git flow init -d
git flow feature start initial-config
#
mkdir -p bin data src
#
touch LICENSE README.md VERSION .gitignore src/main.f90

echo '' > src/main.f90
echo 'program hello' >> src/main.f90
echo '  implicit none' >> src/main.f90
echo '  print *, "Hello, world!"' >> src/main.f90
echo 'end program hello' >> src/main.f90
echo '0.1.0' > VERSION
echo 'bin' > .gitignore
#
git add .
git commit -m 'added: files'
git flow feature finish initial-config
