#!/bin/zsh
#
# name:          init-tex-article.zsh
# version:       see VERSION.md
# synopsis:      initializes a project for `TeX`.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-tex-article ARTICLE_TITLE"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local ARTICLE_TITLE=$1
local TEMPLATE_DIR_PATH="$HOME/github/scripts/tex-templates"
alias mkdir='mkdir -p'

tlmgr update --all

mkdir $ARTICLE_TITLE
cd $ARTICLE_TITLE
#
git flow init -d
#
git flow feature start initial-config
#
wget https://raw.githubusercontent.com/github/gitignore/master/TeX.gitignore -O .gitignore
git add .gitignore
git commit -am "github's .gitignore in place"
#
mkdir -p doc graph sty
git add .
git commit -am "working tree dir established"
#
wget https://raw.githubusercontent.com/idleberg/Creative-Commons-Markdown/spaces/4.0/by-nc.markdown -O LICENSE.md
git add LICENSE.md
git commit -am "CC-BY-NC v.4.0 license (LICENSE.md) in place"
#
cp $HOME/github/scripts/tex-templates/TODO.org ./TODO.org
git add ./TODO.org
git commit -am "TODO.org in place"
#
cp $HOME/github/scripts/tex-templates/VERSION.md ./VERSION.md
git add ./VERSION.md
git commit -am "VERSION.md in place"
#
cp $HOME/github/scripts/tex-templates/references.bib ./doc/references.bib
git add ./doc/references.bib
git commit -am "references file in place"
#
cp $HOME/github/scripts/tex-templates/*.sty ./sty
git add .
git commit -am "template files (.sty) in place"
#
cp $HOME/github/scripts/tex-templates/info.tex ./doc/info.tex
git add .
git commit -am "article info file (info.tex) in place"
#
cp $HOME/github/scripts/tex-templates/abstract.tex ./doc/abstract.tex
git add .
git commit -am "abstract file in place"
#
cp $HOME/github/scripts/tex-templates/theory.tex ./doc/theory.tex
git add .
git commit -am "theory file (dumb file) in place"
#
cp $HOME/github/scripts/tex-templates/main.tex ./$ARTICLE_TITLE.tex
git add .
git commit -am "main file (main.tex) in place"
#
cp $HOME/github/scripts/tex-templates/Nemesis ./Nemesis
sed -i '' -- "s/main.tex/$ARTICLE_TITLE.tex/g" Nemesis
git add .
git commit -am "Nemesis (nemesis builder) file in place"
#
git flow feature finish initial-config
