#!/bin/zsh
#
# name:          init-stack-haskell-project.zsh
# version:       see VERSION.md
# synopsis:      initializes a `stack` project for `Haskell`.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=2
local USAGE="Usage: init-stack-haskell-project PROJECT_NAME STACK_TEMPLATE_NAME"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=$1
local STACK_TEMPLATE_NAME=$2

stack update
stack new $PROJECT_NAME $STACK_TEMPLATE_NAME

cd $PROJECT_NAME
git init
wget https://raw.githubusercontent.com/github/gitignore/master/Haskell.gitignore -O .gitignore
git add .gitignore
git commit -am 'added github .gitignore'
mv LICENSE LICENSE.md
git add LICENSE.md
git commit -am 'added BSD license'
touch CHANGELOG.md README.md TODO.org
git add CHANGELOG.md README.md TODO.org
git commit -am 'added CHANGELOG, README, and TODO'
hasktags -e . > TAGS
mkdir -p reps
git flow init -d
git add .
git commit -am 'git-flow ran and in force'
