#!/bin/zsh
#
# name:          init-cpp-premake-project.zsh
# version:       see VERSION.md
# synopsis:      initialize a `C++`'s `premake` project.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2017 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-cpp-premake-project PROJECT_NAME"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=$1
local SCRIPT_DIR_PATH=$HOME/github/scripts
local TEMPLATE_DIR_PATH=$HOME/github/scripts/cpp-premake-templates

cp -R $TEMPLATE_DIR_PATH $PROJECT_NAME
cd $PROJECT_NAME
echo "project stub files in place"
#
git flow init -d
git flow feature start initial-config
#
wget https://raw.githubusercontent.com/github/gitignore/master/C%2B%2B.gitignore -O .gitignore
git add .gitignore
git commit -am "Github's .gitignore in place"
#
echo "\n# premake" >> .gitignore
echo ".build" >> .gitignore
git add .gitignore
git commit -am "premake artifacts added to .gitignore"
#
wget https://raw.githubusercontent.com/rimbaudcode/scripts/develop/LICENSE.md -O LICENSE.md
git add LICENSE.md
git commit -am "BSD3 license file in place"
#
sed -i '' -- "s/tool_name/$PROJECT_NAME/g" README.md
git add README.md
git commit -am "README.md in place"
#
sed -i '' -- "s/tool_name/$PROJECT_NAME/g" premake5.lua
git add premake5.lua
git commit -am "premake5.lua edited and in place"
#
git add CHANGELOG.org
git commit -m "CHANGELOG.org in place"
#
git add .
git commit -am "project config files in repo"
#
git flow feature finish initial-config
