#!/bin/zsh
#
# name:          init-tex-article.zsh
# version:       see VERSION.md
# synopsis:      initializes a project for `TeX`.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-tex-article ARTICLE_TITLE"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local ARTICLE_TITLE=$1
local TEMPLATE_DIR_PATH="$HOME/github/scripts/tex-templates"
alias mkdir='mkdir -p'

tlmgr update --all

mkdir $ARTICLE_TITLE
cd $ARTICLE_TITLE

git init

wget https://raw.githubusercontent.com/github/gitignore/master/TeX.gitignore -O .gitignore
git add .gitignore
git commit -am "github's .gitignore added"

mkdir -p doc graph sty
git add .
git commit -am "working tree dir added"

wget https://raw.githubusercontent.com/idleberg/Creative-Commons-Markdown/spaces/4.0/by-nc.markdown -O LICENSE.md
git add LICENSE.md
git commit -am "CC-BY-NC license (LICENSE.md) added"

touch TODO.org
git add TODO.org
git commit -am "TODO.org added"

cp $HOME/github/scripts/tex-templates/references.bib ./doc/references.bib
git add ./doc/references.bib
git commit -am "references file (doc/.bib) added"

cp $HOME/github/scripts/tex-templates/*.sty ./sty
git add .
git commit -am "template files (.sty) added"

cp $HOME/github/scripts/tex-templates/info.tex ./doc/info.tex
git add .
git commit -am "article info file (info.tex) added"

cp $HOME/github/scripts/tex-templates/abstract.tex ./doc/abstract.tex
git add .
git commit -am "abstract file (abstract.tex) added"

cp $HOME/github/scripts/tex-templates/theory.tex ./doc/theory.tex
git add .
git commit -am "theory file (theory.tex) added"

cp $HOME/github/scripts/tex-templates/main.tex ./main.tex
git add .
git commit -am "main file (main.tex) added"

cp $HOME/github/scripts/tex-templates/Nemesis ./Nemesis
git add .
git commit -am "Nemesis (nemesis builder file) added"

cp $HOME/github/scripts/tex-templates/main.sublime-project ./$ARTICLE_TITLE.sublime-project
git add .
git commit -am "support for sublimetext project (.sublime-project file) added"

git flow init -d
