#!/bin/zsh
#
# name:          init-swift-project.zsh
# version:       see VERSION.md
# synopsis:      initializes a `swift` project.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-swift-project PROJECT_NAME"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=$1
local SCRIPT_DIR_PATH=$HOME/github/scripts
local TEMPLATE_DIR_PATH=$HOME/github/scripts/swift-templates

mkdir $PROJECT_NAME
cd $PROJECT_NAME
#
git flow init -d
git flow feature start initial-config
#
swift package init --type executable
#
wget https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore -O .gitignore
git add .gitignore
git commit -am "github's .gitignore in place"
#
wget https://raw.githubusercontent.com/rimbaudcode/scripts/develop/LICENSE.md -O LICENSE.md
git add LICENSE.md
git commit -m "BSD3 license in place"
#
cp $TEMPLATE_DIR_PATH/VERSION.md ./VERSION.md
git add VERSION.md
git commit -m "VERSION.md in place"
#
cp $TEMPLATE_DIR_PATH/CHANGELOG.org ./CHANGELOG.org
git add CHANGELOG.org
git commit -m "CHANGELOG.org in place"
#
touch README.md
git add README.md
git commit -am "README.md in place"
#
git add .
git commit -m "swift package files under git"
#
git flow feature finish initial-config
