#!/bin/zsh
#
# name:          init-latex-letter.zsh
# version:       see VERSION.md
# synopsis:      initializes a `TeX` letter.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2017 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=1
local USAGE="Usage: init-latex-letter LETTER_TITLE"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local REPORT_TITLE=$1
local TEMPLATE_DIR_PATH="$HOME/playground/letter-template"
local TEMPLATE_DIR_NAME="letter-template"

tlmgr update --all

cp -r $TEMPLATE_DIR_PATH ./
mv $TEMPLATE_DIR_NAME $REPORT_TITLE
