#!/bin/zsh
#
# name:          install-mint-soft.zsh
# version:       see VERSION.md
# synopsis:      install `mintOS` software
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

# update apps

cd /tmp
sudo apt-get update
sudo apt-get upgrade
sudo apt-get autoremove
sudo apt-get autoclean

# sudo apt-get install zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# sudo apt-get install zsh-syntax-highlighting

# mkdir -p ~/github
# cd ~/github
# git clone https://github.com/wofr06/lesspipe.git
# cd lesspipe
# ./configure
# sudo cp lesspipe.sh code2color /usr/local/bin

# cd ~/github
# git clone https://github.com/rimbaudcode/dotfiles.git
# git clone https://github.com/rimbaudcode/scripts.git
# cd ~/github/scripts
# ./symlinks-mint
# reboot

# install source-code-pro
# * font-manager
cd /tmp
wget -Ok https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
mv k ~/Downloads
cd ~/Downloads

cd /tmp
sudo apt-get install ansiweather
sudo apt-get install coreutils
sudo apt-get install fileutils
sudo apt-get install git-flow
sudo apt-get install glances
sudo apt-get install gnuplot
sudo apt-get install tmux
sudo apt-get install trash-cli
sudo apt-get install tree
sudo apt-get install xdot
sudo apt-get install w3m

sudo apt-get install ranger
ranger --copy-config=all

cd ~/github
git clone https://github.com/rimbaudcode/tao.git
git clone https://github.com/rimbaudcode/tonato.git

sudo apt-get install emacs24-nox
sudo apt-get install libz-dev
sudo apt-get install zlib1g-dev
sudo apt-get install haskell-stack
sudo -k

cd /tmp
stack update
stack new hello simple
cd hello
stack setup
stack build
#
# if it fails, then change the number of cores to 2 and bump the memory up to
# 2GB
stack upgrade --git -j2
reboot
#
cd /tmp
stack update
stack new hello simple
cd hello
stack setup
stack build
stack exec hello

stack install hlint
stack install ghc-mod
stack install pointfree
stack install pointful
stack install stylish-haskell

stack install hoogle
unalias hoogle
hoogle generate

# return to 1 core and 1GB memory in the VM
#
# rm crappy stuff
#
sudo apt-get purge banshee
sudo apt-get purge blueberry
sudo apt-get purge bluetooth
sudo apt-get purge brasero
sudo apt-get purge firefox
sudo apt-get purge gimp
sudo apt-get purge hexchat
sudo apt-get purge libreoffice #
sudo apt-get purge mate-media
sudo apt-get purge mate-screensaver
sudo apt-get purge mate-screensaver-common
sudo apt-get purge pidgin
sudo apt-get purge pix
sudo apt-get purge printer #
sudo apt-get purge simple-scan
sudo apt-get purge thunderbird
sudo apt-get purge tomboy
sudo apt-get purge transmission-common
sudo apt-get purge transmission-gtk
sudo apt-get purge xed
sudo apt-get purge xplayer
sudo apt-get purge xplayer-plugins
sudo apt-get purge xreader
sudo apt-get purge xviewer
#
sudo apt-get autoremove
sudo apt-get autoclean
