#!/bin/zsh
#
# name:          mkhaskell.zsh
# version:       see VERSION.md
# synopsis:      scaffolds `Haskell` projects.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=2
local USAGE="Usage: mkhaskell PROJECT_NAME STACK_TEMPLATE_NAME"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=$1
local STACK_TEMPLATE_NAME=$2

stack update
stack new $PROJECT_NAME $STACK_TEMPLATE_NAME

cd $PROJECT_NAME
wget https://raw.githubusercontent.com/github/gitignore/master/Haskell.gitignore -O .gitignore
mkdir -p reps
mv LICENSE LICENSE.md
touch CHANGELOG.md README.md TODO.org
git init
git commit -am "initial commit"
git flow init -d
