#!/bin/zsh
#
# name:          scatter.sh
# version:       see VERSION.md
# synopsis:      scatter plot CSV data.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

local REQUIRED_ARGC=3
local USAGE="Usage: scatter X_VALUE Y_VALUE CSV_FILE.csv"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local X_VALUE=$1
local Y_VALUE=$2
local CSV_FILE=$3

# $SCRIPTS_PATH is an ENV variable
PLOT_SCRIPT=$HOME/github/scripts/scatter.gp

gnuplot -c $PLOT_SCRIPT $X_VALUE $Y_VALUE $CSV_FILE
