#!/bin/zsh
#
# name:          setup-xcode-swift-project.zsh
# version:       see VERSION.md
# synopsis:      sets up `Xcode`'s `Swift` generated projects.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=0
local USAGE="Usage: setup-xcode-swift-project"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

local PROJECT_NAME=`basename $(pwd)`
local SCRIPT_DIR_PATH=$HOME/github/scripts
local TEMPLATE_DIR_PATH="$HOME/github/scripts/xcode-templates"

git flow init -d
git flow feature start initial-file-seed
#
wget https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore -O .gitignore
git add .gitignore
git commit -am "github's .gitignore in place"
#
cp $TEMPLATE_DIR_PATH/TODO.org ./TODO.org
echo "\n# Emacs\n#\nTODO.org" >> .gitignore
git add .gitignore
git commit -m "TODO.org in place but not tracked by git"
#
sed -i '' -- "s/ProjectName/$PROJECT_NAME/g" TODO.org
#
wget https://raw.githubusercontent.com/rimbaudcode/scripts/develop/LICENSE.md -O ./$PROJECT_NAME/LICENSE.md
git add ./$PROJECT_NAME/LICENSE.md
git commit -m "BSD3 license in place"
#
cp $TEMPLATE_DIR_PATH/Credits.rtf ./$PROJECT_NAME/Credits.rtf
git add ./$PROJECT_NAME/Credits.rtf
git commit -am "Credits.rtf in place"
#
cp $SCRIPT_DIR_PATH/CHANGELOG.md ./CHANGELOG.md
git add CHANGELOG.md
git commit -m "CHANGELOG.md in place"
#
touch README.md
git add README.md
git commit -am "README.md in place"
#
git add .
git commit -am "initial commit of Xcode generated files"
#
git flow feature finish initial-file-seed
