#!/bin/zsh
#
# name:          [name].zsh
# version:       see VERSION.md
# synopsis:      [synopsis here]
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

local REQUIRED_ARGC=2
local USAGE="Usage: [name].zsh ARGUMENTS"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi
