#!/usr/local/bin/zsh
#
# name:          symlinks-mac.zsh
# version:       see VERSION.md
# synopsis:      symlink `macOS` files from `dotfiles` repo in place
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

DOT_FILES_PATH=$HOME/github/dotfiles

ln -is $DOT_FILES_PATH/ansiweatherrc $HOME/.ansiweatherrc
ln -is $DOT_FILES_PATH/ghci $HOME/.ghci
ln -is $DOT_FILES_PATH/gitignore_global $HOME/.gitignore_global
ln -is $DOT_FILES_PATH/nanorc $HOME/.nanorc

ln -is $DOT_FILES_PATH/irssi/config $HOME/.irssi/config
ln -is $DOT_FILES_PATH/mac/gitconfig $HOME/.gitconfig
ln -is $DOT_FILES_PATH/mac/zshrc $HOME/.zshrc

ln -is $DOT_FILES_PATH/micro/settings.json $HOME/.config/micro/settings.json
ln -is $DOT_FILES_PATH/newsbeuter/urls $HOME/.newsbeuter/urls
ln -is $DOT_FILES_PATH/stack/config.yaml $HOME/.stack/config.yaml

rm -i $DOT_FILES_PATH/emacs.d $HOME/.emacs.d
rm -i $DOT_FILES_PATH/sublime/User $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

ln -is $DOT_FILES_PATH/emacs.d $HOME/.emacs.d
ln -is $DOT_FILES_PATH/sublime/User $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

#
echo 'configure ranger'
