#!/bin/zsh
#
# name:          update-xcode-project.zsh
# version:       see VERSION.md
# synopsis:      scaffolds `Swift` projects.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      Programming

local REQUIRED_ARGC=0
local USAGE="Usage: xcode-project"

if (( $# != REQUIRED_ARGC )); then
    echo $USAGE
    exit 1
fi

wget https://raw.githubusercontent.com/rimbaudcode/scripts/develop/LICENSE.md -O LICENSE.md
touch CHANGELOG.md README.md TODO.org
git init
git add .
git commit -am "initial commit"
git flow init -d
