#!/usr/local/bin/zsh
#
# name:          update-apps.zsh
# version:       see VERSION.md
# synopsis:      update `macOS` apps and tools.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

'/Applications/App Store.app/Contents/MacOS/App Store'
'/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop'
'/Applications/Backup and Sync.app/Contents/MacOS/Backup and Sync'
'/Applications/OneDrive.app/Contents/MacOS/OneDrive'
'/Applications/iTunes.app/Contents/MacOS/iTunes'
