#!/usr/local/bin/zsh
#
# name:          update-tools.zsh
# version:       see VERSION.md
# synopsis:      update `macOS` tools.
# license:       BSD3
# license-file:  LICENSE.md
# author:        art rimbaud
# maintainer:    rimbaudcode[at]gmail(DoT)com
# copyright:     (c) 2016 rimbaudcode
# category:      System

brew analytics off
brew update
brew upgrade
brew cleanup
brew prune
brew doctor
#
sh $ZSH/tools/upgrade.sh
#
freshclam
#
stack update
#
#pip install --upgrade pip
#pip install --upgrade pip setuptools
#pip-review --local --auto
pip3 install --upgrade pip setuptools
#
tlmgr update --all
#
load-conda
conda update conda
conda update anaconda
#
sudo gem update --system
sudo gem update
sudo -k
